version: '3.8'
services:
  notabee_mysql:
    container_name: notabee_mysql
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./notabee_mysql:/var/lib/notabee_mysql
  notabee_api:
    container_name: notabee_api
    depends_on:
      - notabee_mysql
    build:
      context: ./api
    ports:
      - "3001:3000"
    volumes:
      - ./api:/usr/src/app/api
    entrypoint: ["sh", "entrypoint.sh"]
  notabee_frontend:
    container_name: notabee_frontend
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    entrypoint: ["sh", "entrypoint.sh"]

